{{- if and .Values.alertmanager.enabled .Values.alertmanager.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-operator.alertmanager.serviceName" . }}
  labels:
    {{- include "prometheus-operator.alertmanager.labels" . | nindent 4 }}
    {{- with .Values.alertmanager.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.alertmanager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.alertmanager.service.type }}
  {{- with .Values.alertmanager.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    {{- toYaml .Values.alertmanager.service.ports | nindent 4 }}
  selector:
    {{- include "prometheus-operator.alertmanager.selectorLabels" . | nindent 4 }}
{{- end }}
